# Generated by Django 4.2.4 on 2023-08-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Впроцессе'), ('done', 'Сделано')], default='new', max_length=50)),
                ('date_of_completion', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'Список дел',
                'db_table': 'To-do list',
            },
        ),
    ]
